## The theme to display: light, dark, grey, auto.
theme: dark

server:
  ## Updated to use the new server address format
  address: tcp://0.0.0.0:9091

log:
  ## Level of verbosity for logs: info, debug, trace.
  level: debug

## JWT secret configuration
identity_validation:
  reset_password:
    jwt_secret: my_very_important_secret

authentication_backend:
  file:
    path: /config/users.yml
    watch: false
    search:
      email: false
      case_insensitive: false
    password:
      algorithm: argon2
      argon2:
        variant: argon2id
        iterations: 3
        memory: 65536
        parallelism: 4
        key_length: 32
        salt_length: 16

totp:
  ## Disable TOTP.
  disable: true

session:
  ## The name of the session cookie.
  name: authelia_session

  ## Multi-domain configuration for modern setups
  cookie:
    domains:
      - mlops.bzh
    same_site: lax

  ## Secret used to sign the session
  secret: unsecure_session_secret

  ## Session expiration and inactivity settings
  expiration: 1h
  inactivity: 5m
  remember_me: true

storage:
  encryption_key: my_very_important_secret
  local:
    path: /config/db.sqlite3

access_control:
  default_policy: one_factor
  rules:
    # Règle générale pour tous les sous-domaines
    - domain: "*.mlops.bzh"
      policy: one_factor
    - domain: "mlflow.mlops.bzh"
      policy: one_factor
    - domain: "labelstudio.mlops.bzh"
      policy: one_factor
    - domain: "minio.mlops.bzh"
      policy: one_factor
    - domain: "neo4j.mlops.bzh"
      policy: one_factor
    - domain: "vault.mlops.bzh"
      policy: one_factor
    - domain: "ssh.mlops.bzh"

notifier:
  filesystem:
    filename: /var/lib/authelia/emails.txt
